services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      TZ: "Asia/Tokyo"
      SERVER_NAME: "Tahiro Server"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
